#!/usr/bin/env python3
"""Generate nationwide Province/Ward seed data from the supplied workbook.

The workbook maps many former wards to the same post-merger ward, so rows are
deduplicated by the exact (province, ward) pair. Hồ Chí Minh is deliberately
left in hcmc-wards.ts because its existing numeric seed codes are already
referenced by live records.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
import unicodedata
import zipfile
from collections import OrderedDict
from pathlib import Path
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "prisma/data/sources/vietnam-sap-nhap-phuong-xa.xlsx"
OUTPUT = ROOT / "prisma/data/nationwide-wards.ts"
HCMC_SOURCE = ROOT / "prisma/data/hcmc-wards.ts"
HCMC_NAME = "Thành phố Hồ Chí Minh"
MAIN_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"


def slug(value: str) -> str:
    value = value.replace("Đ", "D").replace("đ", "d")
    value = "".join(
        char
        for char in unicodedata.normalize("NFD", value)
        if unicodedata.category(char) != "Mn"
    )
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def province_code(name: str) -> str:
    short_name = re.sub(r"^(Tỉnh|Thành phố)\s+", "", name)
    return slug(short_name)


def read_first_sheet(source: Path) -> list[tuple[str, str]]:
    ns = {"m": MAIN_NS}
    with zipfile.ZipFile(source) as archive:
        shared_strings: list[str] = []
        if "xl/sharedStrings.xml" in archive.namelist():
            root = ElementTree.fromstring(archive.read("xl/sharedStrings.xml"))
            shared_strings = [
                "".join(node.text or "" for node in item.findall(".//m:t", ns))
                for item in root.findall("m:si", ns)
            ]

        sheet = ElementTree.fromstring(
            archive.read("xl/worksheets/sheet1.xml")
        )
        pairs: list[tuple[str, str]] = []
        for row in sheet.findall("m:sheetData/m:row", ns)[1:]:
            values: list[str] = []
            for cell in row.findall("m:c", ns):
                value_node = cell.find("m:v", ns)
                value = "" if value_node is None else (value_node.text or "")
                if cell.attrib.get("t") == "s" and value:
                    value = shared_strings[int(value)]
                elif cell.attrib.get("t") == "inlineStr":
                    inline = cell.find("m:is", ns)
                    value = (
                        "".join(
                            node.text or ""
                            for node in inline.findall(".//m:t", ns)
                        )
                        if inline is not None
                        else ""
                    )
                values.append(value.strip())
            if len(values) >= 2 and values[0] and values[1]:
                pairs.append((values[0], values[1]))
        return pairs


def existing_hcmc_wards() -> set[str]:
    source = HCMC_SOURCE.read_text(encoding="utf-8")
    body = source.split("export const HCMC_WARDS: string[] = [", 1)[1].split(
        "];", 1
    )[0]
    return set(re.findall(r'"([^"]+)"', body))


def quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def unique_ward_codes(names: list[str]) -> list[str]:
    """Keep readable codes while disambiguating Unicode spelling variants."""
    codes: list[str] = []
    used: set[str] = set()
    for name in names:
        base = slug(name)
        code = base
        if code in used:
            suffix = hashlib.sha256(name.encode("utf-8")).hexdigest()[:8]
            code = f"{base}-{suffix}"
        if code in used:
            raise RuntimeError(f"Could not generate a unique ward code for {name}")
        used.add(code)
        codes.append(code)
    return codes


def main() -> None:
    source = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_SOURCE
    pairs = read_first_sheet(source)
    unique_pairs = list(dict.fromkeys(pairs))
    provinces: OrderedDict[str, list[str]] = OrderedDict()
    for province, ward in unique_pairs:
        provinces.setdefault(province, []).append(ward)

    if len(provinces) != 34 or len(unique_pairs) != 3321:
        raise RuntimeError(
            f"Expected 34 provinces and 3321 unique wards, got "
            f"{len(provinces)} and {len(unique_pairs)}"
        )

    hcmc_wards = set(provinces.get(HCMC_NAME, []))
    if hcmc_wards != existing_hcmc_wards():
        raise RuntimeError("The workbook's Hồ Chí Minh wards differ from existing seed data")

    generated: list[str] = [
        "// Generated by scripts/import-vietnam-geography.py. Do not edit by hand.",
        f"// Source: {source.name}",
        f"// SHA-256: {hashlib.sha256(source.read_bytes()).hexdigest()}",
        "// 33 provinces below + Hồ Chí Minh in hcmc-wards.ts = 34 provinces,",
        "// 3,321 post-merger wards nationwide.",
        "",
        'import type { ProvinceSeedEntry } from "./provinces-registry";',
        "",
        "export const NATIONWIDE_PROVINCES: ProvinceSeedEntry[] = [",
    ]

    used_province_codes: set[str] = set()
    for province in sorted(name for name in provinces if name != HCMC_NAME):
        code = province_code(province)
        if code in used_province_codes:
            raise RuntimeError(f"Duplicate province code: {code}")
        used_province_codes.add(code)

        wards = provinces[province]
        ward_codes = unique_ward_codes(wards)

        generated.extend(
            [
                "  {",
                f"    province: {{ code: {quote(code)}, name: {quote(province)} }},",
                "    wards: [",
            ]
        )
        generated.extend(
            f"      {{ code: {quote(ward_code)}, name: {quote(name)} }},"
            for ward_code, name in zip(ward_codes, wards)
        )
        generated.extend(["    ],", "  },"])

    generated.extend(["]", ""])
    OUTPUT.write_text("\n".join(generated), encoding="utf-8")
    print(
        f"Generated {OUTPUT.relative_to(ROOT)} from {len(pairs)} rows: "
        f"{len(provinces)} provinces, {len(unique_pairs)} unique wards"
    )


if __name__ == "__main__":
    main()
